export { MoreThanOrEqual, LessThanOrEqual, IsNull } from 'typeorm';
export { getDataSource, ensureDataSource, getDb } from './data-source';
export type { Db } from './data-source';
export type { Repo, RepoWithInsert, FindManyOptions, FindOneOptions } from './db-types';
export { useSupabase, getSupabase } from './supabase-client';
export { RegistryService } from './registry';
export type { IndicatorConfig } from './registry';
export { linearRegressionSlope, classifyTrend, average } from './trend';
export type { Trend } from './trend';
export { StatusEngine } from './status-engine';
export type { Status, StatusResult } from './status-engine';
export { DashboardService } from './dashboard.service';
export { IndicatorsService } from './indicators.service';
export { AlertsService } from './alerts.service';
export { RulesEngine } from './rules-engine';
export type { AlertRuleCondition, AlertRuleJson } from './rules-engine';
export { NotificationService } from './notification.service';
export { ProviderFactory } from './providers/provider.factory';
export type { ProviderAdapter, NormalizedPoint, FetchParams } from './providers/adapter.interface';
export { FredAdapter } from './providers/fred.adapter';
export { CoinGeckoAdapter } from './providers/coingecko.adapter';
export { BinanceAdapter } from './providers/binance.adapter';
export { AlternativeMeAdapter } from './providers/alternative-me.adapter';
export { TwelveDataAdapter } from './providers/twelve-data.adapter';
export * from './entities';
